## Numpy

In [7]:
# Create 1d numpy array
import numpy as np
a = np.array([1,2,3,45,5])
print(type(a))
print(a)
print(a.dtype)
print(a.shape)

<class 'numpy.ndarray'>
[ 1  2  3 45  5]
int32
(5,)


In [9]:
# set datatype when creating numpy array
a = np.array([1,2,3,4,5], dtype = 'float32')
print(a.dtype)
print(a[1], a[-1])

float32
2.0 5.0


In [14]:
# 2d matrix
a = np.array([[1,2,3,4],[4,5,6,8]])
print(a.shape)
print(a[0][0], a[1][1])
print(a[0,3], a[1,3])
print(a)

(2, 4)
1 5
4 8
[[1 2 3 4]
 [4 5 6 8]]


In [16]:
# built in array
a = np.ones((2,2))
print(a)
b = np.zeros((3,3))
print(b)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
# another
a = np.eye(4)
print(a)
b = np.random.random((2,2))
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.34935706 0.98939735]
 [0.62563399 0.54551331]]


## Array Indexing
- [indexing](https://numpy.org/doc/stable/user/quickstart.html)
- [Another link](https://scipy-lectures.org/intro/numpy/array_object.html)

In [28]:
a = np.array([[1,2,3,4], [6,7,8,9], [11,2,22,44]])
print(a)
print('Using index:')
print(a[:2, 1:3])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11  2 22 44]]
Using index:
[[2 3]
 [7 8]]


## Masking
- [check this link](https://www.python-course.eu/numpy_masking.php)
- [Numpy org - Masked Array](https://numpy.org/doc/stable/reference/maskedarray.html)

In [35]:
a = np.array([[12,11], [14,5], [45,1]])
bool_index = (a > 10)
print(bool_index.astype(int))
print('using bool index:', a[bool_index])
print('Direct:', a[a > 10])

[[1 1]
 [1 0]
 [1 0]]
using bool index: [12 11 14 45]
Direct: [12 11 14 45]


In [46]:
a = np.array([[1,2,3], [1,2,3], [4,5,6]])
b = np.array([[7,8,9], [4,7,8], [6,9,8]])

# multiply
print(a * b)
print('Multiplication: \n', np.multiply(a, b))

# Add
print('addition: \n', np.add(a, b))
print('Division: \n', np.divide(a, b))
print('Subtraction: \n', np.subtract(a, b))
print('Sqrt: \n', np.sqrt(a))

[[ 7 16 27]
 [ 4 14 24]
 [24 45 48]]
Multiplication: 
 [[ 7 16 27]
 [ 4 14 24]
 [24 45 48]]
addition: 
 [[ 8 10 12]
 [ 5  9 11]
 [10 14 14]]
Division: 
 [[0.14285714 0.25       0.33333333]
 [0.25       0.28571429 0.375     ]
 [0.66666667 0.55555556 0.75      ]]
Subtraction: 
 [[-6 -6 -6]
 [-3 -5 -5]
 [-2 -4 -2]]
Sqrt: 
 [[1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Numpy reshape

In [48]:
x = np.arange(12)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [50]:
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])